name: funq-cupstacking-timer

services:
  cupstacking-timer:
    build: .
    ports:
      - "23002:80"
    labels:
      - "com.funq.project=true"
      - "com.funq.name=cupstacking-timer"
    restart: unless-stopped